server:
  port: 8081
spring:
  application:
    name: cloud-consumer-order-openfeifn
  # zipkin/sleuth链路跟踪
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      # 采样值介于0到1之间,1表示全部采集
#      probability: 1
eureka:
  client:
    #自己注册到eureka
    register-with-eureka: true
    #是否从rabbion获取已注册信息，默认为true，单节点无所谓，集群只有设置为true才能配合rabbion做负载
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002:7002/eureka,http://eureka7003:7003/eureka
      # 集群版
      # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: customOrder8081
    # 访问路径可以显示ip地址
    prefer-ip-address: true
#ribbon的超时时间
ribbon:
  #读取资源用时
  ReadTimeout: 3000
  #链接时间
  ConnectTimeout: 3000
logging:
  level:
    #日志级别及监控哪个类
    com.ztx.springcloud.service.OrderService: debug
