server:
  port: 9527
spring:
  application:
    name: cloud-getway
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #  消息发送到交换机确认机制,是否确认回调
    publisher-confirm-type: correlated
    #  消息发送到交换机确认机制,是否返回回馈
    publisher-returns: true
  cloud:
    gateway:
      routes:
        #路由id没有固定的规则但要求唯一，建议配合服务名
        - id: payment_routh
          #匹配后提供服务的路由地址
          uri: http://localhost:8001
          predicates:
             #断言，路径相匹配的进行路由
            - Path=/payment/**
            - Cookie=username,ztx       #键值对
        - id: lb_payment_rouths
          uri: lb://cloud-payment-service
          predicates:
            #断言，路径相匹配的进行路由
            - Path=/**
            - Cookie=username,ztx       #键值对curl http://localhost:9527/getprot --cookie "username=ztx"
      enabled: true   #开启路由配置
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由功能，利用微服务进行路由
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7002:7002/eureka,http://eureka7003:7003/eureka
  instance:
    instance-id: getway9527
    # 访问路径可以显示ip地址
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"  #暴露监控端口，可以配置/health等，这里是*，代表全部
