server:
  port: 9003
spring:
  application:
    name: cloud-alibaba-consumer-service
  zipkin:
    base-url: http://localhost:9411/
    sleuth:
      sampler:
        percentage: 1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
service-uri:
  nacos-user-server: http://cloud-alibaba-provider-service/
logging:
  level:
    com.netflix: warn
management:
  endpoints:
    web:
      exposure:
        #监控端口全部暴露
        include: "*"
