server:
  port: 6001
spring:
  application:
    name: cloud-timess-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7002:7002/eureka,http://eureka7003:7003/eureka
  instance:
    instance-id: timeserver6001
    # 访问路径可以显示ip地址
    prefer-ip-address: true