server:
  port: 9527
spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 0
    # redis服务器地址（默认为loaclhost）
    host: 127.0.0.1
    # redis端口（默认为6379）
    post: 6379
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位毫秒）
    timeout: 10000ms
    # redis连接池配置
    jedis:
      pool:
        max-active: 32  # 最大可用连接数（默认为8，负数表示无限）
        max-idle: 32 # 最大空闲连接数（默认为8，负数表示无限）
        min-idle: 0  # 最小空闲连接数（默认为0，该值只有为正数才有用）
        max-wait: 10000ms # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
  application:
    name: cloud-getway
  cloud:
    gateway:
      routes:
        #路由id没有固定的规则但要求唯一，建议配合服务名
        - id: payment_routh
          #匹配后提供服务的路由地址
          uri: http://localhost:8001
          predicates:
             #断言，路径相匹配的进行路由
            - Path=/payment/**
            - Cookie=username,ztx       #键值对
        - id: lb_payment_rouths
          uri: lb://cloud-payment-service
          predicates:
            #断言，路径相匹配的进行路由
            - Path=/**
            - Cookie=username,ztx       #键值对curl http://localhost:9527/getprot --cookie "username=ztx"
      enabled: true   #开启路由配置
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由功能，利用微服务进行路由
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://127.0.0.1:7002/eureka,http://127.0.0.1:7003/eureka
  instance:
    instance-id: getway9527
    # 访问路径可以显示ip地址
    prefer-ip-address: true
